package bl4ckscor3.mod.xptome;

import java.util.Arrays;

import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.AnvilUpdateEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;

@Mod(modid=XPTome.MODID, name=XPTome.NAME, version=XPTome.VERSION, acceptedMinecraftVersions="[" + XPTome.MC_VERSION + "]")
@EventBusSubscriber
public class XPTome
{
	public static final String MODID = "xpbook";
	public static final String NAME = "XP Tome";
	public static final String VERSION = "v1.1.2";
	public static final String MC_VERSION = "1.12.2";
	@ObjectHolder(MODID + ":" + ItemXPTome.NAME)
	public static final Item XP_BOOK = null;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList("bl4ckscor3");
		meta.autogenerated = false;
		meta.description = "Adds a book that can store a limited amount of XP.";
		meta.modId = MODID;
		meta.name = NAME;
		meta.version = VERSION;
	}

	@SubscribeEvent
	public static void onRegisterItems(RegistryEvent.Register<Item> event)
	{
		event.getRegistry().register(new ItemXPTome().setRegistryName(new ResourceLocation(MODID, ItemXPTome.NAME)).setTranslationKey(MODID + ":" + ItemXPTome.NAME));
	}

	@SubscribeEvent
	public static void onAnvilUpdate(AnvilUpdateEvent event)
	{
		if(event.getLeft().getItem() == XP_BOOK || event.getRight().getItem() == XP_BOOK)
			event.setCanceled(true);
	}
}
