# Project
group=bl4ckscor3.mod.xptome
version=2.5.1
minecraft_version=26.2
minecraft_min_version=26.2
java_version=25
license=MIT
mod_id=xpbook
mod_name=XP Tome
description=Adds a book that can store a configurable amount of XP.
mod_author=bl4ckscor3
minecraft_version_range=[26,)
source_link=https://github.com/bl4ckscor3/XP-Tome
cf_link=https://www.curseforge.com/minecraft/mc-mods/xp-tome

# Common
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2
mdg_version=2.0.147
fcap_version=26.2.1
run_dir=../runs
mixin_version=0.13.3+mixin.0.8.5
mixinextras_version=0.3.5

# NeoForge
neoforge_version=26.2.0.88
neoforge_min_version=26

# Fabric
loom_version=1.17-SNAPSHOT
fabric_version=0.161.0+26.2
fabric_loader_version=0.19.5
modmenu_version=21.0.0-beta.1

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
