modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/XP-Tome/blob/1.21.3/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/XP-Tome/issues"

[[mods]]
	modId="xpbook"
	version="${file.jarVersion}"
	displayName="XP Tome"
	description='''Adds a book that can store a configurable amount of XP.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/xp-tome"
	authors="bl4ckscor3"

[[mixins]]
    config="xptome.mixins.json"

[[dependencies.xpbook]]
    modId="neoforge"
    type="required"
    versionRange="[21.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpbook]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.2,1.22)"
    ordering="NONE"
    side="BOTH"